### PR TITLE
STACK-45-copyToClipboard

### PR DESCRIPTION
**Pull request by MarMil1**
- Implemented copyToClipboard function
- Parsed asked and answered question date
- Added style to answers page
- On questions view, see into the question by clicking on the eye icon
- On answers view, go back by clicking the green arrow

### CODE REVIEW

**Comment by brightpk** [comment]
Looks good! Just one thing I found is that when I click to see answers, go back to the question page and click on the same question again, the copy and insert buttons are gone.

**Comment by brightpk** [comment]
> Looks good! Just one thing I found is that when I click to see answers, go back to the question page and click on the same question again, the copy and insert buttons are gone.

**Comment by MarMil1** [comment]
I see what you mean. Good catch! I'll take a look at it.

**Comment by MarMil1** [comment]
It should be working now. Thanks guys!

**Pull request merged**
